### ISSUE TITLE
Great theme, thank you!

### ISSUE THREAD

**Issue by mentalisttraceur** [ArmandPhilippot/coldark#1]
I just came across your theme because a recent update to Git Delta made its default syntax colors unusable for me, and your `Coldark-Dark` (for `bat`) was the *only* theme it shipped with that was as readable as I'd like!

In particular, I want to compliment your choice of color for comments! Almost everyone else makes comments a dingy gray which becomes barely visible if the background color changes, such as in diffs, but yours remain legible, even *easy* to read in most cases:

![Screenshot_20240319-002712](https://github.com/ArmandPhilippot/coldark/assets/6531708/be1d73f2-1198-4f96-b15a-f1de23834d9b)

![Screenshot_20240319-003148](https://github.com/ArmandPhilippot/coldark/assets/6531708/d0dceb1e-9a3d-430a-83f0-66cd7112eec8)

Thank you so much for putting in the time and effort to make such a considerate theme!

**Comment by ArmandPhilippot** [comment]
Wow thanks for you review! I'm glad to see I'm not the only one who thinks that most of the themes are hard to read...

But I have to admit this one is not perfect neither. It's not easy to make the theme readable for all cases when the colors are limited. I'm still having trouble figuring out how to improve the terminal port: with tools like `vimdiff` it is often unreadable...

I just open the `Discussions` section, so I'm moving this topic there to keep `Issues` for real issues. Thanks again, it's nice to see that others like this theme too!
